#----------------------------------------------------------------
# Generated CMake target import file for configuration "RelWithDebInfo".
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Import target "SAMRAI_algs" for configuration "RelWithDebInfo"
set_property(TARGET SAMRAI_algs APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SAMRAI_algs PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX;Fortran"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib64/libSAMRAI_algs.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS SAMRAI_algs )
list(APPEND _IMPORT_CHECK_FILES_FOR_SAMRAI_algs "${_IMPORT_PREFIX}/lib64/libSAMRAI_algs.a" )

# Import target "SAMRAI_appu" for configuration "RelWithDebInfo"
set_property(TARGET SAMRAI_appu APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SAMRAI_appu PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX;Fortran"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib64/libSAMRAI_appu.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS SAMRAI_appu )
list(APPEND _IMPORT_CHECK_FILES_FOR_SAMRAI_appu "${_IMPORT_PREFIX}/lib64/libSAMRAI_appu.a" )

# Import target "SAMRAI_geom" for configuration "RelWithDebInfo"
set_property(TARGET SAMRAI_geom APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SAMRAI_geom PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX;Fortran"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib64/libSAMRAI_geom.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS SAMRAI_geom )
list(APPEND _IMPORT_CHECK_FILES_FOR_SAMRAI_geom "${_IMPORT_PREFIX}/lib64/libSAMRAI_geom.a" )

# Import target "SAMRAI_hier" for configuration "RelWithDebInfo"
set_property(TARGET SAMRAI_hier APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SAMRAI_hier PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib64/libSAMRAI_hier.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS SAMRAI_hier )
list(APPEND _IMPORT_CHECK_FILES_FOR_SAMRAI_hier "${_IMPORT_PREFIX}/lib64/libSAMRAI_hier.a" )

# Import target "SAMRAI_math" for configuration "RelWithDebInfo"
set_property(TARGET SAMRAI_math APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SAMRAI_math PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib64/libSAMRAI_math.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS SAMRAI_math )
list(APPEND _IMPORT_CHECK_FILES_FOR_SAMRAI_math "${_IMPORT_PREFIX}/lib64/libSAMRAI_math.a" )

# Import target "SAMRAI_mesh" for configuration "RelWithDebInfo"
set_property(TARGET SAMRAI_mesh APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SAMRAI_mesh PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX;Fortran"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib64/libSAMRAI_mesh.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS SAMRAI_mesh )
list(APPEND _IMPORT_CHECK_FILES_FOR_SAMRAI_mesh "${_IMPORT_PREFIX}/lib64/libSAMRAI_mesh.a" )

# Import target "SAMRAI_pdat" for configuration "RelWithDebInfo"
set_property(TARGET SAMRAI_pdat APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SAMRAI_pdat PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX;Fortran"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib64/libSAMRAI_pdat.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS SAMRAI_pdat )
list(APPEND _IMPORT_CHECK_FILES_FOR_SAMRAI_pdat "${_IMPORT_PREFIX}/lib64/libSAMRAI_pdat.a" )

# Import target "SAMRAI_solv" for configuration "RelWithDebInfo"
set_property(TARGET SAMRAI_solv APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SAMRAI_solv PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX;Fortran"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib64/libSAMRAI_solv.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS SAMRAI_solv )
list(APPEND _IMPORT_CHECK_FILES_FOR_SAMRAI_solv "${_IMPORT_PREFIX}/lib64/libSAMRAI_solv.a" )

# Import target "SAMRAI_tbox" for configuration "RelWithDebInfo"
set_property(TARGET SAMRAI_tbox APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SAMRAI_tbox PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib64/libSAMRAI_tbox.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS SAMRAI_tbox )
list(APPEND _IMPORT_CHECK_FILES_FOR_SAMRAI_tbox "${_IMPORT_PREFIX}/lib64/libSAMRAI_tbox.a" )

# Import target "SAMRAI_xfer" for configuration "RelWithDebInfo"
set_property(TARGET SAMRAI_xfer APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(SAMRAI_xfer PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "${_IMPORT_PREFIX}/lib64/libSAMRAI_xfer.a"
  )

list(APPEND _IMPORT_CHECK_TARGETS SAMRAI_xfer )
list(APPEND _IMPORT_CHECK_FILES_FOR_SAMRAI_xfer "${_IMPORT_PREFIX}/lib64/libSAMRAI_xfer.a" )

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
