# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget SAMRAI_algs SAMRAI_appu SAMRAI_geom SAMRAI_hier SAMRAI_math SAMRAI_mesh SAMRAI_pdat SAMRAI_solv SAMRAI_tbox SAMRAI_xfer)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# The installation prefix configured by this project.
set(_IMPORT_PREFIX "/g/g17/wood67/src/cleverleaf/apollo-test/RelWithDebInfo/install/SAMRAI")

# Create imported target SAMRAI_algs
add_library(SAMRAI_algs STATIC IMPORTED)

set_target_properties(SAMRAI_algs PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "SAMRAI_hier;SAMRAI_tbox;SAMRAI_pdat"
)

# Create imported target SAMRAI_appu
add_library(SAMRAI_appu STATIC IMPORTED)

set_target_properties(SAMRAI_appu PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "SAMRAI_hier;SAMRAI_pdat;SAMRAI_tbox;/usr/lib64/libhdf5.so;/usr/lib64/libsz.so;/usr/lib64/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so"
)

# Create imported target SAMRAI_geom
add_library(SAMRAI_geom STATIC IMPORTED)

set_target_properties(SAMRAI_geom PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "SAMRAI_hier;SAMRAI_pdat;SAMRAI_tbox"
)

# Create imported target SAMRAI_hier
add_library(SAMRAI_hier STATIC IMPORTED)

set_target_properties(SAMRAI_hier PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/tce/packages/mvapich2/mvapich2-2.3-gcc-4.9.3/include;/usr/tce/packages/mvapich2/mvapich2-2.3-gcc-4.9.3/include;/usr/tce/packages/mvapich2/mvapich2-2.3-gcc-4.9.3/include;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "SAMRAI_tbox;/usr/tce/packages/mvapich2/mvapich2-2.3-gcc-4.9.3/lib/libmpi.so;/usr/tce/packages/mvapich2/mvapich2-2.3-gcc-4.9.3/lib/libmpicxx.so;/usr/tce/packages/mvapich2/mvapich2-2.3-gcc-4.9.3/lib/libmpi.so;/usr/tce/packages/mvapich2/mvapich2-2.3-gcc-4.9.3/lib/libmpifort.so;/usr/tce/packages/mvapich2/mvapich2-2.3-gcc-4.9.3/lib/libmpi.so"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "/usr/tce/packages/mvapich2/mvapich2-2.3-gcc-4.9.3/include;/usr/tce/packages/mvapich2/mvapich2-2.3-gcc-4.9.3/include;/usr/tce/packages/mvapich2/mvapich2-2.3-gcc-4.9.3/include"
)

# Create imported target SAMRAI_math
add_library(SAMRAI_math STATIC IMPORTED)

set_target_properties(SAMRAI_math PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "SAMRAI_hier;SAMRAI_pdat;SAMRAI_tbox"
)

# Create imported target SAMRAI_mesh
add_library(SAMRAI_mesh STATIC IMPORTED)

set_target_properties(SAMRAI_mesh PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "SAMRAI_hier;SAMRAI_tbox;SAMRAI_xfer"
)

# Create imported target SAMRAI_pdat
add_library(SAMRAI_pdat STATIC IMPORTED)

set_target_properties(SAMRAI_pdat PROPERTIES
  INTERFACE_COMPILE_OPTIONS "\$<\$<NOT:\$<COMPILE_LANGUAGE:Fortran>>:-fopenmp>;\$<\$<COMPILE_LANGUAGE:Fortran>:-fopenmp>"
  INTERFACE_INCLUDE_DIRECTORIES "/g/g17/wood67/src/cleverleaf/apollo-test/RelWithDebInfo/install/RAJA/include;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "SAMRAI_hier;SAMRAI_tbox;SAMRAI_xfer;RAJA"
)

# Create imported target SAMRAI_solv
add_library(SAMRAI_solv STATIC IMPORTED)

set_target_properties(SAMRAI_solv PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "SAMRAI_hier;SAMRAI_math;SAMRAI_tbox;SAMRAI_xfer"
)

# Create imported target SAMRAI_tbox
add_library(SAMRAI_tbox STATIC IMPORTED)

set_target_properties(SAMRAI_tbox PROPERTIES
  INTERFACE_COMPILE_OPTIONS "\$<\$<NOT:\$<COMPILE_LANGUAGE:Fortran>>:-fopenmp>;\$<\$<COMPILE_LANGUAGE:Fortran>:-fopenmp>"
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include;/usr/tce/packages/mvapich2/mvapich2-2.3-gcc-4.9.3/include;/usr/tce/packages/mvapich2/mvapich2-2.3-gcc-4.9.3/include;/usr/tce/packages/mvapich2/mvapich2-2.3-gcc-4.9.3/include;/g/g17/wood67/src/cleverleaf/apollo-test/RelWithDebInfo/install/Umpire/include;/g/g17/wood67/src/apollo/install/include;/g/g17/wood67/src/cleverleaf/apollo-test/RelWithDebInfo/install/RAJA/include;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "/usr/lib64/libhdf5.so;/usr/lib64/libsz.so;/usr/lib64/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so;/usr/tce/packages/mvapich2/mvapich2-2.3-gcc-4.9.3/lib/libmpi.so;/usr/tce/packages/mvapich2/mvapich2-2.3-gcc-4.9.3/lib/libmpicxx.so;/usr/tce/packages/mvapich2/mvapich2-2.3-gcc-4.9.3/lib/libmpi.so;/usr/tce/packages/mvapich2/mvapich2-2.3-gcc-4.9.3/lib/libmpifort.so;/usr/tce/packages/mvapich2/mvapich2-2.3-gcc-4.9.3/lib/libmpi.so;umpire;/g/g17/wood67/src/apollo/install/lib/libapollo.so;RAJA"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "/usr/tce/packages/mvapich2/mvapich2-2.3-gcc-4.9.3/include;/usr/tce/packages/mvapich2/mvapich2-2.3-gcc-4.9.3/include;/usr/tce/packages/mvapich2/mvapich2-2.3-gcc-4.9.3/include"
)

# Create imported target SAMRAI_xfer
add_library(SAMRAI_xfer STATIC IMPORTED)

set_target_properties(SAMRAI_xfer PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "SAMRAI_hier"
)

if(CMAKE_VERSION VERSION_LESS 2.8.12)
  message(FATAL_ERROR "This file relies on consumers using CMake 2.8.12 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/SAMRAITargets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
